server:
  port: 18080

spring:
  datasource:
    url: jdbc:mysql://114.115.182.205:3306/reliable-message?useUnicode=true&characterEncoding=utf-8
    username: techfish
    password: Techfish.2018
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: chennan753

# dubbo配置
dubbo:
  application:
    name: rmq-service
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20890
  scan:
    base-packages: com.cn.rmq.service.impl