
dubbo:
  application:
    name: rmq-check
    logger: slf4j
  registry:
    address: zookeeper://127.0.0.1:2181
  scan:
    base-packages: com.cn.rmq.schedule.service.impl

schedule:
  check:
    core-pool-size: 10
    max-pool-size: 100
    keep-alive-time: 60000
    queue-capacity: 10
    wait-complete-timeout: 10000
  recover:
    max-times: 6
    core-pool-size: 10
    max-pool-size: 100
    keep-alive-time: 60000
    queue-capacity: 10
    wait-complete-timeout: 10000