
dubbo:
  application:
    name: rmq-check
    logger: slf4j
  registry:
    address: zookeeper://127.0.0.1:2181
  scan:
    base-packages: com.cn.rmq.schedule.service.impl

schedule:
  check:
    core-pool-size: 1
    max-pool-size: 1
    keep-alive-seconds: 60
    queue-capacity: 1
  recover:
    max-times: 6