
dubbo:
  application:
    name: rmq-check
    logger: slf4j
  registry:
    address: zookeeper://127.0.0.1:2181
  scan:
    base-packages: com.cn.rmq.check.schedule

schedule:
  check:
    max-duration-times: 10
  recover:
    max-times: 6